project:
  type: website

website:
  title: KGCompetitors
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-final-KGCompetitors # Need to change to your project repo -- changed
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
